language: go
go:
  - 1.12.x
os:
  - linux
dist: trusty
sudo: false
install: true

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
